name = 'Hacked Hugo'
license = 'MIT'
licenselink = 'https://github.com/sbroekhoven/Hacked-Hugo/blob/main/LICENSE
description = 'Hacked based theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/sbroekhoven/Hacked-Hugo'

# If you have a running demo of the theme
demosite = 'https://github.com/sbroekhoven/Hacked-Hugo'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']


# If the theme has a single author
[author]
  name = 'Sebastian Broekhoven'
  homepage = 'https://github.com/sbroekhoven'
